### PR TITLE
Create on assignment

### LINKED ISSUE #6: First Assignment
> I guess it would make sense to only make a chat room on the first assignment

_Originally posted by @0x4007 in https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/5#issuecomment-2408895453_

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #6

- `createchat` runs on `issues.assigned`
- we look for an existing chat using the `node_id` and skip if it exists

QA:

view the payload event for `issues.assigned` and confirm chat via logs or [join here](https://t.me/+orF-n39-xo42MWZk)

Chat creation:
https://github.com/ubq-testing/telegram--bot/actions/runs/11447419429/job/31848699310

Skipping creation if exists:
https://github.com/ubq-testing/telegram--bot/actions/runs/11447435712/job/31848754535

Cloudflare deployed and operational:
image

image

### CODE REVIEW

**Comment by Keyrxng** [comment]
Bot is deployed to a ubiquity CF worker and is responding on TG. 

https://github.com/ubiquity/.ubiquity-os/commit/c9852df14ab31c8c1f8a22f4292a4fcae5ea6001 I just tried to install in `Ubiquity` in the prod config but no response and I don't have access to debug.

I think I need access to a .dev config, @gentlementlegen @0x4007 rfc?


image

**Comment by Keyrxng** [comment]
Actually I'm just going to merge it into development now because the config is setup for that I believe, worth a shot rather than waiting, if it fails I'll need assistance with updating the config.

**Comment by gentlementlegen** [comment]
The current configuration on this repository looks like
```yaml
  - uses:
      - plugin: ubiquity-os-marketplace/ubiquity-os-kernel-telegram@development
        with:
          botId: 7543249164
  - uses:
      - plugin: https://ubiquity-os-telegram-bridge-development.ubiquity.workers.dev
        with:
          botId: 7543249164
```

**Comment by Keyrxng** [comment]
https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions/workflows/compute.yml

I don't understand why there are no workflows being dispatched to this repo at all and I have made a couple of attempts over the past 2-3 days.

The botfather bot https://t.me/UbiquityOS_Beta_Bot is responding via the worker. 

Ubiquity-os-beta[bot] is clearly repling to me in this repo.

Could you take a peak at the kernel worker logs and try to kick off a run for me when you have a minute please? Config is the same as mine

```yml
   - uses:
     - plugin: https://ubiquity-os-telegram-bridge-create-on-assignment.keyrxng7749.workers.dev 
       with:
         botId: 7543249164
   - uses:
     - plugin: ubq-testing/telegram--bot:compute.yml@create-on-assignment
       with: 
         botId: 7543249164
```

---

I've never had issues like this and I don't with interactions between my kernel and workflow. My #3 is fully operational with private DMs and GH storage, not once did this happen across my development so without seeing the prod logs I'm stumped.

**Comment by Keyrxng** [comment]
https://github.com/ubiquity-os-marketplace/command-ask/actions/runs/11474342941

LMAO. I just installed `Ubiquity-os-beta[bot]` github app to my org and it won't dispatch from org to the ubiquity kernel either

**Comment by Keyrxng** [comment]
@gentlementlegen @rndquu Can one of you install my kernel to this org for me please? I will uninstall it after I am finished which will be tonight.


image

**Comment by rndquu** [comment]
> @gentlementlegen @rndquu Can one of you install my kernel to this org for me please? I will uninstall it after I am finished which will be tonight.
> 
> It's only this repo I'm asking installing it to
> 
> image

I don't have much context regarding this PR, so I can't install a new app with pretty sensitive permissions without any context, I'll check the PR today

**Comment by Keyrxng** [comment]
I'm admin on this repo if that helps I have all of the same permissions that the app will request pretty much.

but sure thing, thank you.

**Comment by Keyrxng** [comment]
The issue was that the kernel wasn't responding because it is now looking to accept a `signature`, which is why the runs were not kicking off.

@gentlementlegen made that change (I wasn't aware we were going back passing sigs) and everything is working fine

**Pull request merged**
